name: PR Tests

on: pull_request
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.300
      - name: Install dependencies
        run: dotnet restore
      - name: Install tools
        run: dotnet tool restore
      - name: Check format
        run: dotnet fantomas --check -r .
      - name: Test
        run: dotnet test --no-restore --verbosity normal
